### PR TITLE
update modulefile to use stable parallel ESMF build

### PR DESCRIPTION
**Pull request by zacharyburnettNOAA**
fixes https://github.com/noaa-ocs-modeling/ADC-WW3-NWM-NEMS/issues/53

### CODE REVIEW

**Comment by zacharyburnettNOAA** [comment]
approve and / or squash merge this whenever you are able; I have tested this in the build

**Comment by pvelissariou1** [comment]
Zach,
Is this for 7be503f?
I see no review button


Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
USM - Stennis Space Center
cell: (205) 227-9141
email: ***@***.***

**Comment by zacharyburnettNOAA** [comment]
> Zach, Is this for [7be503f](https://github.com/noaa-ocs-modeling/ADC-WW3-NWM-NEMS/commit/7be503f24f81f412fdfa3c850a38c9088a64799c)? I see no review button

yes that's correct, you should be able to review by going to the [Files changed](https://github.com/noaa-ocs-modeling/ADC-WW3-NWM-NEMS/pull/54/files) tab

**Review by pvelissariou1 — APPROVED** [review]
Will re-examine to incorporate a stable release of esmf. It is ok for now.

**Pull request merged**
