### PR TITLE
ADCIRC v55

### PR DESCRIPTION
**Pull request by zacharyburnettNOAA**
implemented @pvelissariou1 patch for ADCIRC v55 to the ADCIRC repository and also each submodule

### CODE REVIEW

**Comment by zacharyburnettNOAA** [comment]
comparison of ADCIRC updates: https://github.com/moghimis/adcirc-cg/compare/59765040a3716ec51b00266710bc8b1b58c48a4c...6a43e9f1299e311283d9115e4dd35c0e24aafced

**Comment by zacharyburnettNOAA** [comment]
The build  fails on Hera: #19

**Comment by zacharyburnettNOAA** [comment]
both ADCIRC and NEMS now build successfully; now testing

**Comment by saeed-moghimi-noaa** [comment]
Great!
______________________________________________________
Saeed Moghimi, PhD
UCAR/NOAA - NOS Storm Surge Modeling Team Lead
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910
Phone: (240) 847-8230
Email: Saeed.moghimi@noaa.gov
Web Page <https://sites.google.com/site/moghimis/home>

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.

**Comment by zacharyburnettNOAA** [comment]
these changes are built on top of @GM-Ling 's changes in #7

**Review by saeed-moghimi-noaa — APPROVED** [review]

**Comment by saeed-moghimi-noaa** [comment]
@zacharyburnettNOAA 
Hi Zach, I have merged the branch. Good luck. -Saeed

**Pull request merged**
